[[plugins]]
  package = "@netlify/angular-runtime"

[functions]
  # This tells Netlify where your SSR entry point is
  included_files = ["dist/sc-www/server/**"]

[build]
  command = "ng build --configuration=netlify"
  publish = "dist/sc-www/browser"

# If your project uses a specific environment variable for the server path:
[build.environment]
  ANGULAR_PACKAGE_JSON_PATH = "package.json"
